### ISSUE TITLE
video-item

### ISSUE THREAD

**Issue by ramillard** [wyllyan/tubber#1]
Is there a way to interact with each video-item (or it's thumbnail) individually, or am I limited to manipulating all of them at the same time via the .video-item class?  I'm looking to add a 'now playing' overlay to the active item.

Awesome plugin, thanks.

**Comment by wyllyan** [comment]
Thank you!

You can control the active video item through the “active” class. If you want, you’re able to change it setting the option “videoItemActiveClass”. As example about what you’re looking, is possible to add an element in the template option. See:

``` javascript
templates: {
    videoItem: '<div class="now-playing"></div>{{video_media}}{{video_title}}{{video_description}}'
}
```

But is more simple to use a pseudo class with the "video-item” element:

``` css
.video-item::after {
    /*style code for playing now*/
}
```

Here is an example that can help you: https://jsfiddle.net/ma7y9e08/

**Comment by ramillard** [comment]
That's fantastic, and it worked like a charm.  Thank you.

Keep up the good work with the plugin.

**Comment by wyllyan** [comment]
You’re very welcome!

I’m glad that it worked for you.
Thanks. Improvements will come to make it better.
